<a href="https://colab.research.google.com/github/arnabaghorai/FederatedLearning/blob/master/FL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# !pip install syft

In [2]:
# Run this cell to see if things work
import sys

import torch
from torch.nn import Parameter
import torch.nn as nn
import torch.nn.functional as F

import syft as sy
hook = sy.TorchHook(torch)



Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.15.3.so'


In [3]:
x = torch.tensor([1,2,3,4,5])
y = x + x
print(y)

tensor([ 2,  4,  6,  8, 10])


In [0]:
bob = sy.VirtualWorker(hook, id="bob")

In [0]:
x_ptr = x.send(bob)
y_ptr = y.send(bob)

In [6]:
x_ptr.owner

<VirtualWorker id:me #objects:0>

In [0]:
z = x_ptr + y_ptr

In [11]:
z.location

<VirtualWorker id:bob #objects:3>

In [0]:
me = sy.local_worker

In [14]:
bob == z.owner

False

In [16]:
z.get()

tensor([ 3,  6,  9, 12, 15])

In [19]:
bob._objects

{98178170124: tensor([ 2,  4,  6,  8, 10])}

In [18]:
x_ptr.get()

tensor([1, 2, 3, 4, 5])